### ISSUE TITLE
Module under linux x64 not work with message getaddrinfo ENOTFOUND undefined

### ISSUE THREAD

**Issue by federicopepe** [bitfocus/companion-module-netio-powerbox#5]
from version 3.0.0-rc2 onwards in both the stable version and the beta version I get the following log:

24.01.05 18:24:58 Instance/Wrapper/PowerBOX: getaddrinfo ENOTFOUND undefined
24.01.05 18:24:59 Instance/Wrapper/PowerBOX: Child is not running, unable to send message: {"direction":"call","name":"variablesChanged","payload":"{\"variablesIds\":[\"internal:time_hms\",\"internal:time_s\",\"internal:time_unix\",\"internal:time_hms_12\"]}"}
24.01.05 18:24:59 Instance/ModuleHost: Registered module client "PJCaEZ1ACkK8QoL-bWpfX"
24.01.05 18:24:59 Instance/Controller: instance "PowerBOX" configuration updated

and the interface doesn't open in connection -> Edit connection , retry keeps appearing

**Comment by jorbje** [comment]
I have the exact same problem. Raspberry Pi with CompanionOS. Just upgraded to v3.2.2

**Comment by SNRSE** [comment]
Hey @jorbje  and @federicopepe can you please try again as soon as the latest Version is out ? i did a lot of fixes to make it more stable and this shouldn't happened anymore

**Comment by jorbje** [comment]
We moved Companion over to a small Windows PC. There the Powerboxes work perfectly. But great that you have tried to fix it for Linux. I hope someone else can enjoy that :)
JB

    On Tuesday, May 14, 2024 at 12:09:58 AM GMT+2, Jonas Dautel ***@***.***> wrote:  
 
 


Hey @jorbje and @federicopepe can you please try again as soon as the latest Version is out ? i did a lot of fixes to make it more stable and this shouldn't happened anymore
